package com.github.drtrang.typehandlers.domain;

import java.io.Serializable;
import java.util.Date;

public class BaseCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.code_type
     *
     * @mbg.generated
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.code_value
     *
     * @mbg.generated
     */
    private String codeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_base_code.is_encrypt
     *
     * @mbg.generated
     */
    private Boolean isEncrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_base_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.id
     *
     * @return the value of m_base_code.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.id
     *
     * @param id the value for m_base_code.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.code_type
     *
     * @return the value of m_base_code.code_type
     *
     * @mbg.generated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.code_type
     *
     * @param codeType the value for m_base_code.code_type
     *
     * @mbg.generated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.code_value
     *
     * @return the value of m_base_code.code_value
     *
     * @mbg.generated
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.code_value
     *
     * @param codeValue the value for m_base_code.code_value
     *
     * @mbg.generated
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.remark
     *
     * @return the value of m_base_code.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.remark
     *
     * @param remark the value for m_base_code.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.create_time
     *
     * @return the value of m_base_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.create_time
     *
     * @param createTime the value for m_base_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.update_time
     *
     * @return the value of m_base_code.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.update_time
     *
     * @param updateTime the value for m_base_code.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_base_code.is_encrypt
     *
     * @return the value of m_base_code.is_encrypt
     *
     * @mbg.generated
     */
    public Boolean getIsEncrypt() {
        return isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_base_code.is_encrypt
     *
     * @param isEncrypt the value for m_base_code.is_encrypt
     *
     * @mbg.generated
     */
    public void setIsEncrypt(Boolean isEncrypt) {
        this.isEncrypt = isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_base_code
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", codeType=").append(codeType);
        sb.append(", codeValue=").append(codeValue);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isEncrypt=").append(isEncrypt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}