package com.github.trang.typehandlers.mapper;

import java.util.List;

import com.github.trang.typehandlers.domain.BaseCode;

public interface BaseCodeOriginMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CODE
     *
     * @mbg.generated
     */
    int insert(BaseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CODE
     *
     * @mbg.generated
     */
    BaseCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CODE
     *
     * @mbg.generated
     */
    List<BaseCode> selectAll();

    List<BaseCode> selectByRemark(String remark);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CODE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseCode record);
}